version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - mern-net-social-media
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  backend:
    build: ./server
    container_name: server
    networks:
      - mern-net-social-media
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB=mongodb://root:root@mongo:27017/mern-app-social-media?authSource=admin
      - JWT_KEY = "MERN"
      - PORT = 5000


  frontend:
    build: ./client
    container_name: client
    networks:
      - mern-net-social-media
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - REACT_APP_PUBLIC_FOLDER = http://localhost:5000/images/

networks:
  mern-net-social-media:
    driver: bridge
